---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERPORT=51820 #optional
      - SERVERURL = lab.riklabs.com
      - PEERS=rikPixel,edieLaptop,rikLaptop
      - PEERDNS=192.168.1.1
      - LOG_CONFS=true #optional
    volumes:
      - /home/rikw/docker/appdata/wireguard:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
